version: 2

sources:
  - name: erpnorthwind
    description: Fonte de dados
    tables:
      - name: public_orders
        columns:
        - name: order_id
          description: Chave primária
      - name: public_order_details
      - name: public_products
      - name: public_employees
      - name: public_customers
      - name: public_suppliers